[phases.setup]
nixPkgs = ["python311", "gcc"]
aptPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd frontend && npm ci --prefer-offline --no-audit"
]

[phases.build]
cmds = ["bash build.sh"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 api:app"
